#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 960
#define WINDOW_HEIGHT 540
#define TARGET_FPS 60
#define FRAME_TIME_MS 16

#define HORIZON_Y 145
#define RUNWAY_BOTTOM_Y 472
#define PLAYER_BASE_Y 455
#define PLAYER_WIDTH 82
#define PLAYER_HEIGHT 112
#define PLAYER_SLIDE_WIDTH 112
#define PLAYER_SLIDE_HEIGHT 54
#define PLAYER_JUMP_SPEED 790.0f
#define PLAYER_DIVE_SPEED -980.0f
#define GRAVITY 2200.0f
#define SLIDE_DURATION 0.45f
#define INVINCIBLE_DURATION 3.0f

#define LANE_COUNT 3
#define LANE_BOTTOM_SPACING 180
#define LANE_MOVE_SPEED 14.0f

#define MAX_OBSTACLES 18
#define OBSTACLE_START_DEPTH 1.08f
#define OBSTACLE_REMOVE_DEPTH -0.18f
#define HIT_DEPTH_MIN -0.045f
#define HIT_DEPTH_MAX 0.085f
#define MIN_GROUP_DEPTH_GAP 0.46f
#define MIN_SPAWN_INTERVAL 1.05f
#define MAX_SPAWN_INTERVAL 1.35f
#define LOW_BARRIER_WIDTH 78
#define LOW_BARRIER_HEIGHT 42
#define HIGH_BARRIER_WIDTH 114
#define HIGH_BARRIER_HEIGHT 70
#define HIGH_BARRIER_GAP 68
#define TRAIN_BLOCK_WIDTH 118
#define TRAIN_BLOCK_HEIGHT 168

#define DEBUG_HITBOX 0
#define DEBUG_ASSET_MARKERS 0

#define START_SPEED 360.0f
#define MAX_SPEED 780.0f
#define SPEED_GAIN_PER_SECOND 12.0f
#define BOOST_MULTIPLIER 1.35f

#define PLAYER_START_HP 3

#define CHARACTER_COUNT 4

#define CHAR_RUNNER_HP        3
#define CHAR_RUNNER_SPEED     1.00f
#define CHAR_RUNNER_INVINCIBLE 3.0f
#define CHAR_RUNNER_GRAVITY    GRAVITY
#define CHAR_RUNNER_JUMP       PLAYER_JUMP_SPEED

#define CHAR_SPRINTER_HP        2
#define CHAR_SPRINTER_SPEED     1.10f
#define CHAR_SPRINTER_GAIN_MULT 1.40f
#define CHAR_SPRINTER_INVINCIBLE 3.0f
#define CHAR_SPRINTER_GRAVITY   GRAVITY
#define CHAR_SPRINTER_JUMP      PLAYER_JUMP_SPEED

#define CHAR_TANK_HP        5
#define CHAR_TANK_SPEED     1.00f
#define CHAR_TANK_GAIN_MULT 0.55f
#define CHAR_TANK_INVINCIBLE 5.0f
#define CHAR_TANK_GRAVITY   GRAVITY
#define CHAR_TANK_JUMP      PLAYER_JUMP_SPEED

#define CHAR_JUMPER_HP        3
#define CHAR_JUMPER_SPEED     1.00f
#define CHAR_JUMPER_INVINCIBLE 3.0f
#define CHAR_JUMPER_GRAVITY   (GRAVITY * 0.78f)
#define CHAR_JUMPER_JUMP      (PLAYER_JUMP_SPEED * 1.18f)

#define MAX_HIGH_SCORES 10
#define NAME_MAX_LENGTH 16
#define NAME_INPUT_LENGTH 8

#define JUMP_BUFFER_WINDOW 0.12f
#define HIT_FREEZE_MS 50
#define HIT_FLASH_MS 150

#define PANEL_MARGIN 40
#define PANEL_COLOR RGB(18, 22, 32)
#define PANEL_BORDER RGB(58, 74, 96)
#define PANEL_TITLE_COLOR RGB(244, 215, 118)
#define PANEL_TEXT_COLOR RGB(200, 210, 224)
#define PANEL_HIGHLIGHT_COLOR RGB(255, 238, 146)
#define HUD_BAR_COLOR RGB(12, 16, 24)
#define HUD_BAR_ALPHA 180

#endif
